#!/usr/bin/env node
/**
 * ═══════════════════════════════════════════════════════════════════════════════
 * SunPage Report Generator — tools/report.js
 * ═══════════════════════════════════════════════════════════════════════════════
 * Writes docs/BUDGET_VICTORIA.md from the same engine and budget code the app
 * uses, so the published numbers always match the tool.
 *
 * Usage: node tools/report.js
 * ═══════════════════════════════════════════════════════════════════════════════
 */

const fs = require('fs');
const path = require('path');
const D = require('../data.js');
const E = require('../engine.js');
const B = require('../budget.js');
const S = require('../settings.js');
const Search = require('../ui/search.js');

const s = S.defaults();
const d = E.buildDesign(s);
const sim = E.simulateSteadyYear(d, { keepHourly: false });
const T = sim.totals;
const cap = B.capex(d);
const lifeDispatch = E.lifecycleDispatch(d);
const life = B.lifecycle(d, lifeDispatch.kwh, cap, lifeDispatch.starts);
const sd = d.minimums.stringDesign;

const money = (v) => '$' + Math.round(v).toLocaleString('en-CA');
const kwh = (v) => Math.round(v).toLocaleString('en-CA') + ' kWh';
const n1 = (v) => v.toFixed(1);
const out = [];
const w = (line) => out.push(line === undefined ? '' : line);

// ── Strategy comparison over 20 weather years ──────────────────────────────
function strategyStats(strategy) {
  const runs = [];
  for (let seed = 1; seed <= 20; seed++) {
    runs.push(E.simulateSteadyYear(Object.assign({}, d, { weatherMode: 'variable', weatherSeed: seed }), { strategy }).totals);
  }
  const q = (arr, p) => arr.slice().sort((a, b) => a - b)[Math.min(arr.length - 1, Math.floor(p * arr.length))];
  const mean = (arr) => arr.reduce((a, b) => a + b, 0) / arr.length;
  return {
    genP50: q(runs.map((r) => r.gen), 0.5), genP90: q(runs.map((r) => r.gen), 0.9),
    costMean: mean(runs.map((r) => r.genCost)), costP90: q(runs.map((r) => r.genCost), 0.9),
    starts: q(runs.map((r) => r.genStarts), 0.5)
  };
}
const smart = strategyStats('smart');
const socS = strategyStats('soc');

// ── Optimizer: the same search and tier rules as the app (ui/search.js) ────
const search = Search.run(s);
const feas = search.rows.filter((r) => r.feasible);
const tier = (id) => search.tiers.find((t) => t.id === id || t.also.includes(Search.TIERS.find((x) => x.id === id).rule));
const rec = search.tiers.find((t) => t.recommended).row;
const cheapestAvg = search.averageBest;
const minCap = tier('essential').row;

// ── Document ────────────────────────────────────────────────────────────────
w('# Off-Grid Solar + Battery System — High-Fidelity Budget, Victoria BC');
w();
w('> Generated by `node tools/report.js` from the same engine as the SunPage app. Do not edit by hand — change the inputs in `settings.js` / `data.js` and regenerate.');
w();
w('## 1. Recommended design');
w();
w('| Component | Qty | Basis |');
w('|---|---:|---|');
w(`| JA Solar JAM54D41-440/LB (440 W) | ${d.panels} | ${n1(d.pvKw)} kWp, ${d.layout.count} strings of ${[...new Set(d.layout.strings)].join('/')} modules |`);
w(`| EG4 FlexBOSS21 | ${d.inverters} | ${d.designPeakKw} kW design peak ÷ 12 kW battery-only; ≤ 21 kW PV each; one per GridBOSS |`);
w(`| EG4 GridBOSS | ${d.gridboss} | ${d.serviceA} A service ÷ 200 A per GridBOSS |`);
w(`| EG4 280Ah All-Weather battery | ${d.batteries} | ${n1(d.batteryKwh)} kWh nominal, ${n1(d.usableKwh)} kWh usable (20 % floor); ≥ 600 Ah per inverter |`);
w(`| 200 A panel | ${Math.ceil(d.serviceA / 200)} | One per GridBOSS load output |`);
w('| BE7500ID 6 kW generator | 1 (existing) | Moved to GridBOSS GEN port with 2-wire auto-start |');
w();
w('### Peak-demand basis (planning assumption)');
w();
w('| Coincident load | Demand |');
w('|---|---:|');
D.PEAK_LOADS.forEach((x) => w(`| ${x.load} | ${n1(x.kw)} kW |`));
w(`| **Total planning peak** | **${n1(D.PEAK_LOADS.reduce((a, x) => a + x.kw, 0))} kW** |`);
w();
w('This is an illustrative coincident-load schedule used to size the inverter minimum, not measured demand. Replace it with a licensed electrical load calculation before construction.');
w();
w('### Performance (year 1, day-to-day weather, weather year ' + d.weatherSeed + ')');
w();
w('| Metric | Value |');
w('|---|---:|');
w(`| Annual load incl. inverter idle + battery heaters | ${kwh(T.load)} |`);
w(`| PV production (DC) | ${kwh(T.pv)} |`);
w(`| Solar share of load | ${(T.solarFraction * 100).toFixed(1)} % |`);
w(`| Generator energy | ${kwh(T.gen)} (${T.genStarts} starts, ${T.genHours} h) |`);
w(`| Generator cost (fuel + carbon-price add-on + service) | ${money(T.genCost)} |`);
w(`| Curtailed PV (zero export) | ${kwh(T.curtailed)} |`);
w(`| Unserved energy | ${kwh(T.unserved)} |`);
D.SEASONS.forEach((se) => {
  const a = E.autonomy(d, se.id, 14, true), z = E.autonomy(d, se.id, 14, false);
  w(`| ${se.name} backup, no generator (average sun / zero sun) | ${a.capped ? '14+' : n1(a.days)} days / ${n1(z.days)} days |`);
});
w();
w('### PV string check (challenge Voc,max formula)');
w();
w(`- Voc,max = 38.9 V × (1 + (${d.designLowC} − 25) × (−0.250)/100) = **${sd.vocColdV.toFixed(2)} V** (design low ${d.designLowC} °C, below Victoria's −15.0 °C record)`);
w(`- Electrical maximum = ⌊550 V MPPT protection / ${sd.vocColdV.toFixed(2)}⌋ = **${sd.maxSeries}**; min = **${sd.minSeries}** (hot Vmp ${sd.vmpHotV.toFixed(1)} V ≥ 250 V full-power window)`);
w(`- **Design maximum = ${sd.series} modules/string.** Eleven modules give cold Vmp ${n1(sd.series * sd.vmpColdV)} V < 440 V full-power ceiling; 12 would be ${n1(12 * sd.vmpColdV)} V and is not used.`);
w(`- Longest string cold Voc ${n1(Math.max(...d.layout.strings) * sd.vocColdV)} V < 550 V < 600 V max; up to two parallel strings on MPPT 1/2 give Isc 2 × 14.3 = 28.6 A < 31 A (one string on the 19 A MPPT).`);
w();
w('### Preliminary one-line notes — verify in final electrical design');
w();
w('- **GridBOSS count:** two units are retained because each GridBOSS is 200 A service equipment and the stated service is 400 A: one unit per 200 A leg. A 200 A service setting uses one unit.');
w('- **Battery protection:** show one 350 A Class-T fuse per inverter positive lead. A 2/0 Cu lead listed at 175 A is only a preliminary concept; the licensed electrical designer must select conductor ampacity, any parallel conductors, terminations and OCPD as one coordinated assembly.');
w('- **Neutral / ground:** make exactly one neutral–ground bond at the off-grid main disconnect. Keep the generator neutral floating unless the generator manufacturer and licensed installer specify a listed switched-neutral arrangement.');
w('- **Battery location:** batteries are assumed indoors, so battery-heater energy is 0 h/day by default. Add a heater load only for an outdoor installation.');
w();
w('## 2. Capital budget (City of Victoria)');
w();
w('| Category | Item | Qty | Unit | Unit cost | Total | PST | Notes |');
w('|---|---|---:|---|---:|---:|:---:|---|');
cap.lines.forEach((l) => {
  const qty = l.qty % 1 ? l.qty.toFixed(1) : l.qty;
  w(`| ${l.category} | ${l.item} | ${qty} | ${l.unit} | ${money(l.unitCost)} | ${money(l.total)} | ${l.pst ? '7 %' : '—'} | ${l.note} |`);
});
w();
w('| Summary | Amount |');
w('|---|---:|');
Object.keys(cap.byCategory).forEach((c) => w(`| ${c} | ${money(cap.byCategory[c])} |`));
w(`| **Pre-tax total** | **${money(cap.subtotal)}** |`);
w(`| PST 7 % on taxable goods (${money(cap.pstBase)}) | ${money(cap.pst)} |`);
w(`| GST 5 % (${money(cap.gstBase)}, permit fees excluded) | ${money(cap.gst)} |`);
w(`| **Total installed cost** | **${money(cap.total)}** ($${(cap.total / (d.pvKw * 1000)).toFixed(2)}/W) |`);
w();
w('**Victoria-specific items**');
w();
w('- **Electrical permit** — City of Victoria contractor fee: $441 + 1.25 % of work value over $20,000, with owner-supplied equipment included in the value.');
w('- **Building permit** — needed for the ground/carport-mounted share of the array: $100 application + 1.40 % of construction value. Roof mounts that meet the City\'s load/attachment/height conditions don\'t need one, but they do need a structural letter and module-level rapid shutdown (CEC Rule 64-218).');
w('- **PST** — BC PST Bulletin 203 exempts PV panels, and the wiring, controllers and DC→AC devices bought as part of a PV system. **Batteries are explicitly not exempt**, and neither are general electrical items (panelboards, disconnect, splitter). The GridBOSS is treated as an exempt PV-system controller; confirm that with the supplier.');
w('- **Incentives** — none included. BC Hydro\'s solar and battery rebates require a grid-connected, net-metered system; this design exports nothing.');
w('- **Freight** — Vancouver Island delivery at ' + d.freightPct + ' % of equipment value.');
w();
w('## 3. Operating & lifecycle cost (' + d.horizonYears + ' years, ' + d.discountPct + ' % discount, ' + d.escalationPct + ' %/yr escalation)');
w();
w('| Year | Gen kWh | Generator | Services | Gen. replaced | O&M | Standby utility | Replacements | Total |');
w('|---:|---:|---:|---:|:---:|---:|---:|---:|---:|');
life.years.forEach((y) => {
  w(`| ${y.year} | ${Math.round(y.genKwh)} | ${money(y.generator)} | ${y.genServices} | ${y.genReplacements ? 'yes' : ''} | ${money(y.om)} | ${money(y.utility)} | ${money(y.inverters + y.batteries)} | ${money(y.total)} |`);
});
w();
w(`- Capital: **${money(life.capex)}**`);
w(`- NPV of operating costs: **${money(life.npvOpex)}** (${money(life.nominalOpex)} nominal)`);
w(`- **Lifecycle cost (NPV): ${money(life.lifecycle)}**`);
w();
w('Generator model: ' + money(d.genCostPerKwh) + '/kWh ÷ current efficiency, plus ' + money(d.genCarbonPricePerKwh) + '/kWh carbon-price add-on, ' + money(d.genServiceCost) + ' service every 100 kWh, efficiency × 0.98 per service, service count carried across years, and replacement (' + money(d.genReplaceCost) + ', assumption) once efficiency falls below ' + Math.round(d.genReplaceAtEff * 100) + ' %. The carbon-price default is $0/kWh because BC eliminated its carbon tax and the federal consumer fuel charge ceased in 2025; it remains adjustable for a future charge or internal carbon value.');
w();
w('## 4. Generator automation — strategy comparison (20 weather years)');
w();
w('| Strategy | Gen kWh P50 | Gen kWh P90 | Mean year-1 cost | P90 cost | Starts P50 |');
w('|---|---:|---:|---:|---:|---:|');
w(`| Forecast-aware (recommended) | ${kwh(smart.genP50)} | ${kwh(smart.genP90)} | ${money(smart.costMean)} | ${money(smart.costP90)} | ${smart.starts} |`);
w(`| SOC trigger (${d.socStartPct} % → ${d.socStopPct} %) | ${kwh(socS.genP50)} | ${kwh(socS.genP90)} | ${money(socS.costMean)} | ${money(socS.costP90)} | ${socS.starts} |`);
w();
w(`Forecast-aware dispatch saves **${money(socS.costMean - smart.costMean)}/yr (${((socS.costMean - smart.costMean) / socS.costMean * 100).toFixed(0)} %)** on this design. It only charges the battery enough to reach the next forecast solar surplus, so generator energy doesn't displace sun that would otherwise be curtailed.`);
w();
w('## 5. Design alternatives (optimizer)');
w();
w(`Every panels × batteries mix is simulated in each of ${search.years} weather years and costed over ${d.horizonYears} years (lifecycle NPV). The stated objective is **minimax**: select the design with the lowest cost in the worst simulated year. Average cost is reported as context, not used to override that decision. These are the tiers on the app's Suggestions tab.`);
w();
w('| Tier | Rule | Panels | Batteries | Inverters | Capex | Gen kWh/yr (avg) | Lifecycle NPV, average | Lifecycle NPV, worst year |');
w('|---|---|---:|---:|---:|---:|---:|---:|---:|');
search.tiers.forEach((t) => {
  const r = t.row;
  const name = t.recommended ? `**${t.n} · ${t.name} (recommended)**` : `${t.n} · ${t.name}`;
  w(`| ${name} | ${[t.rule].concat(t.also).join(' Also: ')} | ${r.panels} | ${r.batteries} | ${r.inverters} | ${money(r.capex)} | ${Math.round(r.genKwh)} | ${money(r.lifecycle)} | ${money(r.worstLifecycle)} |`);
});
w();
w(`${search.rows.length} candidates simulated (${feas.length} meet every requirement in every year). Near the optimum the lifecycle-cost surface is flat. ` +
  (rec === cheapestAvg
    ? 'The recommended design is also the cheapest on average. '
    : `The cheapest design on average is ${cheapestAvg.panels} panels / ${cheapestAvg.batteries} batteries / ${cheapestAvg.inverters} inverters at ${money(cheapestAvg.lifecycle)}. ` +
      `The recommended ${rec.panels} / ${rec.batteries} / ${rec.inverters} averages ${((rec.lifecycle / cheapestAvg.lifecycle - 1) * 100).toFixed(1)} % more, ` +
      `but needs ${money(cheapestAvg.capex - rec.capex)} less capital${cheapestAvg.inverters > rec.inverters ? ' and ' + (cheapestAvg.inverters - rec.inverters) + ' fewer inverter(s)' : ''} ` +
      `and has the lowest worst-year cost of any design (${money(rec.worstLifecycle)} vs ${money(cheapestAvg.worstLifecycle)}). `) +
  `The cheapest compliant build saves ${money(rec.capex - minCap.capex)} up front but costs ${money(minCap.lifecycle - rec.lifecycle)} more over its life on average, because generator fuel and servicing (≈ $4.65+/kWh) cost far more than extra panels (≈ $0.80/W).`);
w();
w('## 6. Context — the same load on BC Hydro');
w();
const householdKwh = D.SEASONS.reduce((a, se) => a + E.seasonalDailyLoad(se, d.springBaseKwh) * 365 / 4, 0);
w(`${kwh(householdKwh)}/yr on BC Hydro's April 2026 residential rate costs about **${money(B.bcHydroAnnual(householdKwh))}/yr** incl. GST. Off-grid operation in Victoria is justified by independence and resilience, not by bill savings.`);
w();
w('## Sources');
w();
D.SOURCES.forEach((src) => w(src.url ? `- [${src.label}](${src.url})` : `- ${src.label}`));

const file = path.resolve(__dirname, '../docs/BUDGET_VICTORIA.md');
fs.mkdirSync(path.dirname(file), { recursive: true });
fs.writeFileSync(file, out.join('\n') + '\n');
console.log('Wrote ' + path.relative(process.cwd(), file));
